#!/usr/local/bin/tclsh
# ==================================================================
# FILE: aux/vimtags
# $Id$
# ---
# tclreadline -- gnu readline for tcl
# https://github.com/flightaware/tclreadline/
# Copyright (c) 1998 - 2014, Johannes Zellner <johannes@zellner.org>
# This software is copyright under the BSD license.
# ==================================================================


if [file readable tags] {
    set tags [open tags r]
    set vim [open tags.vim w]
    while {[gets $tags line] != -1} {
        if [regexp "^\(\[^  !\]*\)\[    \]" $line all proc] {
            set proc [string trim $proc]
            if {$proc != ""} {
                puts $vim "syntax keyword Tag $proc"
            }
        }
    }
    close $tags
    close $vim
}

