#!/usr/local/bin/tclsh
# ==================================================================
# FILE: "/home/joze/bin/script/vimtags"
# LAST MODIFIED: "Thu Oct 01 13:20:11 1998 (joze)"
# (c) 1998 by Johannes Zellner
# Johannes.Zellner@physik.uni-karlsruhe.de
# $Id$
# ================================================================== 


if [file readable tags] {
    set tags [open tags r]
    set vim [open tags.vim w]
    while {[gets $tags line] != -1} {
        if [regexp "^\(\[^ 	!\]*\)\[ 	\]" $line all proc] {
            set proc [string trim $proc]
            if {$proc != ""} {
                puts $vim "syntax keyword Tag $proc"
            }
        }
    }
    close $tags
    close $vim
}

